### ISSUE TITLE
"decoder_input_ids=None" cause error

### ISSUE THREAD

**Issue by LHL3341** [YunxinLi/NDCR#1]
when training the model, I encountered the bug below:

Exception has occurred: AttributeError
'NoneType' object has no attribute 'shape'
  File "/home/NDCR/OFA/transformers/src/transformers/models/ofa/modeling_ofa.py", line 1901, in forward
    ~encoder_outputs.padding_mask, encoder_hidden_states.dtype, decoder_input_ids.shape[-1]
  File "/home/NDCR/OFA_encoder_Divide_and_Conquer.py", line 204, in forward
    gen = self.OFA(input_ids_context, patch_images=global_image, decoder_input_ids=None)
  File "/home/NDCR/OFA_encoder_Divide_and_Conquer.py", line 742, in <module>
    contextual_clip(images, text, pos_mask, None, str(img_dir), text_=None, input_ids=input_ids)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by YunxinLi** [comment]
When we train NDCR, we only use the encoder of OFA to obtain the image representation, thus we set decoder_input_ids=None. In addition, we use self.OFA = OFAModel.from_pretrained(file path) where codes of OFA model in "OFA/transformers/src/transformers/models/ofa/modeling_ofa.py" has been modified to adapt to decoder_input_ids = None.

**Comment by LHL3341** [comment]
> When we train NDCR, we only use the encoder of OFA to obtain the image representation, thus we set decoder_input_ids=None. In addition, we use self.OFA = OFAModel.from_pretrained(file path) where codes of OFA model in "OFA/transformers/src/transformers/models/ofa/modeling_ofa.py" has been modified to adapt to decoder_input_ids = None.

感谢您的解答！
此外我还遇到一个问题，我在通过`contextual_clip.load_state_dict(checkpoint['model_state_dict'])`加载预训练模型pretrain_BART_generator_coldstart_OFA.pt 时，模型参数无法完全匹配从而导致报错，具体错误如下：
Error(s) in loading state_dict for ContextualCLIP:
	Missing key(s) in state_dict: "mapping_network_alignment.1.weight", "mapping_network_alignment.1.bias", "mapping_network_alignment.4.weight", "mapping_network_alignment.4.bias", "negation.0.weight", "negation.0.bias", "negation.3.weight", "modifier.0.weight", "modifier.0.bias", "modifier.3.weight", "modifier.3.bias". 
	Unexpected key(s) in state_dict: "nega.0.weight", "nega.0.bias", "nega.3.weight", "pan.1.weight", "pan.1.bias", "pan.4.weight", "pan.4.bias", "pan_.1.weight", "pan_.1.bias", ......

**Comment by YunxinLi** [comment]
你好，这个版本的代码整理过，一些模块在模型代码中已删除，导致了这个错误，可以设置load state dict 里面的 strict=False 解决。---- Replied Message ***@***.***>Date07/09/2023 20:16 ***@***.***> CcYunxin ***@***.***>***@***.***>SubjectRe: [YunxinLi/NDCR] "decoder_input_ids=None" cause error (Issue #1)

When we train NDCR, we only use the encoder of OFA to obtain the image representation, thus we set decoder_input_ids=None. In addition, we use self.OFA = OFAModel.from_pretrained(file path) where codes of OFA model in "OFA/transformers/src/transformers/models/ofa/modeling_ofa.py" has been modified to adapt to decoder_input_ids = None.

感谢您的解答！
此外我还遇到一个问题，我在通过contextual_clip.load_state_dict(checkpoint['model_state_dict'])加载预训练模型pretrain_BART_generator_coldstart_OFA.pt 时，模型参数无法完全匹配从而导致报错，具体错误如下：
Error(s) in loading state_dict for ContextualCLIP:
Missing key(s) in state_dict: "mapping_network_alignment.1.weight", "mapping_network_alignment.1.bias", "mapping_network_alignment.4.weight", "mapping_network_alignment.4.bias", "negation.0.weight", "negation.0.bias", "negation.3.weight", "modifier.0.weight", "modifier.0.bias", "modifier.3.weight", "modifier.3.bias".
Unexpected key(s) in state_dict: "nega.0.weight", "nega.0.bias", "nega.3.weight", "pan.1.weight", "pan.1.bias", "pan.4.weight", "pan.4.bias", "pan_.1.weight", "pan_.1.bias", ......

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/YunxinLi/NDCR/issues/1#issuecomment-1627699031",
"url": "https://github.com/YunxinLi/NDCR/issues/1#issuecomment-1627699031",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LHL3341** [comment]
好的，谢谢

**Comment by hazardout** [comment]
题主你好，请问第一个问题是怎么解决的

**Comment by YunxinLi** [comment]
你好，请问你说的是decoder id =None 吗？
---- Replied Message ----
***@***.***>Date07/06/2024 20:20 ***@***.***> CcYunxin ***@***.***>,
***@***.***>SubjectRe: [YunxinLi/NDCR] "decoder_input_ids=None" cause error (Issue #1)
作者你好，请问第一个问题是怎么解决的

**Comment by hazardout** [comment]
我在"OFA/transformers/src/transformers/models/ofa/modeling_ofa.py" 里添加了对decoder_input_ids = None情况的处理，不知道是不是这样就可以了呢，代码已跑通
